languageCode = 'en-us'
title = 'Union.ai Docs'
theme = 'union'
disableKinds = ["RSS"]

[params]
_merge = "deep"
show_inactive = false
highlight_active = false
signup_link = "https://www.union.ai/pricing"
variant_selector_order = ["flyte", "byoc", "serverless"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

#----------------------------------------------------------
# Keywords

[params.key]

[params.key.default_project]
flyte = "flytesnacks"
serverless = "default"
byoc = "flytesnacks"
byok = "flytesnacks"

[params.key.product_full_name]
flyte = "Flyte OSS"
serverless = "Union.ai Serverless"
byoc = "Union.ai BYOC"
byok = "Union.ai BYOK"

[params.key.product_name]
flyte = "Flyte"
serverless = "Union.ai"
byoc = "Union.ai"
byok = "Union.ai"

[params.key.product]
flyte = "flyte"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.kit_name]
flyte = "Flytekit"
serverless = "Union"
byoc = "Union"
byok = "Union"

[params.key.kit]
flyte = "flytekit"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.kit_as]
flyte = "fl"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.kit_import]
flyte = "flytekit as fl"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.kit_remote]
flyte = "FlyteRemote"
serverless = "UnionRemote"
byoc = "UnionRemote"
byok = "UnionRemote"

[params.key.cli_name]
flyte = "Pyflyte"
serverless = "Union"
byoc = "Union"
byok = "Union"

[params.key.cli]
flyte = "pyflyte"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.ctl_name]
flyte = "Flytectl"
serverless = "Uctl"
byoc = "Uctl"
byok = "Uctl"

[params.key.ctl]
flyte = "flytectl"
serverless = "uctl"
byoc = "uctl"
byok = "uctl"

[params.key.config_env]
flyte = "FLYTECTL_CONFIG"
serverless = "UNION_CONFIG"
byoc = "UNION_CONFIG"
byok = "UNION_CONFIG"

[params.key.env_prefix]
flyte = "FLYTE"
serverless = "UNION"
byoc = "UNION"
byok = "UNION"

[params.key.docs_home]
flyte = "https://www.union.ai/docs/flyte"
serverless = "https://www.union.ai/docs/serverless"
byoc = "https://www.union.ai/docs/byoc"
byok = "https://www.union.ai/docs/byok"

[params.key.map_func]
flyte = "map_task"
serverless = "map"
byoc = "map"
byok = "map"

[params.key.logo]
flyte = "icon-logo-flyte.png"
serverless = "icon-logo.svg"
byoc = "icon-logo.svg"
byok = "icon-logo.svg"

#----------------------------------------------------------
# Search

[params.search.flyte]
app_id = "2GHFU8TPNP"
search_key = "8cd3a91e81b0144a79682e1d3ecacad4"
index_name = "flyte"

[params.search.byoc]
app_id = "2K3A78HTBR"
search_key = "bfaa8204d151b099b681edb41052a152"
index_name = "byoc"

[params.search.byok]
app_id = "TIVM6MJAB2"
search_key = "f32eb3c993ec93ee561914edafadc25a"
index_name = "byok"

[params.search.serverless]
app_id = "FEI16F3Z8H"
search_key = "e4d47384fcfed00c31afe99c06b69288"
index_name = "serverless"
