[params]
# List of available versions. Format: v<major>.<minor>
versions = [
  "v2",
  "v1",
]

show_deprecation_message = false

# Set legacy version number
# current_version = "<do-not-set>" # set by build
