languageCode = 'en-us'
title = 'Union.ai Docs'
theme = 'union'
disableKinds = ["RSS"]

[params]
_merge = "deep"
variant_hide_in_development = true
variant_identify_variant_in_development = false

#----------------------------------------------------------
# Variables (keyed per variant)

[params.var]

[params.var.default_project]
flyte = "flytesnacks"
serverless = "default"
byoc = "flytesnacks"
byok = "flytesnacks"

[params.var.product_full]
flyte = "Flyte"
serverless = "Union Serverless"
byoc = "Union BYOC"
byok = "Union BYOK"

[params.var.product_upper]
flyte = "Flyte"
serverless = "Union"
byoc = "Union"
byok = "Union"

[params.var.product_lower]
flyte = "flyte"
serverless = "union"
byoc = "union"
byok = "union"

[params.var.kit_upper]
flyte = "Flytekit"
serverless = "Union"
byoc = "Union"
byok = "Union"

[params.var.kit_lower]
flyte = "flytekit"
serverless = "union"
byoc = "union"
#byok = "union"

[params.var.cli_upper]
flyte = "Pyflyte"
serverless = "Union"
byoc = "Union"
byok = "Union"

[params.var.cli_lower]
flyte = "pyflyte"
serverless = "union"
byoc = "union"
byok = "union"

[params.var.ctl_upper]
flyte = "Flytectl"
serverless = "Uctl"
byoc = "Uctl"
byok = "Uctl"

[params.var.ctl_lower]
flyte = "flytectl"
serverless = "uctl"
byoc = "uctl"
byok = "uctl"

[params.var.at_task]
flyte = "@fl.task"
serverless = "@union.task"
byoc = "@union.task"
byok = "@union.task"

[params.var.at_workflow]
flyte = "@fl.workflow"
serverless = "@union.workflow"
byoc = "@union.workflow"
byok = "@union.workflow"
