# hugo.toml - Core configuration for the site builder
#
# Only add settings here that *never* changes.
#
# For site-specific settings, use hugo.site.toml.
# For variant-specific settings, use config.<variant>.toml.

languageCode = 'en-us'
theme = 'union'
disableKinds = ["RSS"]

[params]
_merge = "deep"
show_inactive = false
highlight_active = false

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

#----------------------------------------------------------
# Search

[params.search.flyte]
app_id = "854NZC4U4K"
search_key = "a013df09b48c1317f0bad3605c1840e4"
index_name = "union"

[params.search.byoc]
app_id = "JXAX1VOSS0"
search_key = "f90406df1c8707c844facf29564446dc"
index_name = "union"

[params.search.selfmanaged]
app_id = "ZK72K15QRI"
search_key = "59e5451a3db8540ee70dc8dd04fe6287"
index_name = "union"

[params.search.serverless]
app_id = "L21F4ROAJM"
search_key = "f34fa663e9e327dd7e79526567e5027f"
index_name = "union"
