languageCode = 'en-us'
title = 'Union.ai Docs'
theme = 'union'
disableKinds = ["RSS"]

[params]
_merge = "deep"
show_inactive = false
highlight_active = false

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

#----------------------------------------------------------
# Keywords

[params.key]

[params.key.default_project]
flyte = "flytesnacks"
serverless = "default"
byoc = "flytesnacks"
byok = "flytesnacks"

[params.key.product_full_name]
flyte = "Flyte"
serverless = "Union Serverless"
byoc = "Union BYOC"
byok = "Union BYOK"

[params.key.product_name]
flyte = "Flyte"
serverless = "Union"
byoc = "Union"
byok = "Union"

[params.key.product]
flyte = "flyte"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.kit_name]
flyte = "Flytekit"
serverless = "Union"
byoc = "Union"
byok = "Union"

[params.key.kit]
flyte = "flytekit"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.kit_as]
flyte = "fl"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.kit_import]
flyte = "flytekit as fl"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.cli_name]
flyte = "Pyflyte"
serverless = "Union"
byoc = "Union"
byok = "Union"

[params.key.cli]
flyte = "pyflyte"
serverless = "union"
byoc = "union"
byok = "union"

[params.key.ctl_name]
flyte = "Flytectl"
serverless = "Uctl"
byoc = "Uctl"
byok = "Uctl"

[params.key.ctl]
flyte = "flytectl"
serverless = "uctl"
byoc = "uctl"
byok = "uctl"

[params.key.config_env]
flyte = "FLYTECTL_CONFIG"
serverless = "UNION_CONFIG"
byoc = "UNION_CONFIG"
byok = "UNION_CONFIG"
