name = "Union.AI"
description = "Union site style with language variant support"
homepage = "https://docs.union.ai/"
tags = ["docs", "documentation", "responsive"]
features = ["language variants", "sidebar navigation"]
min_version = "0.41.0"

[author]
  name = "Nelson Araujo"
  homepage = "https://github.com/unionai/docs-builder/tree/main/themes/union"
