name = "docs-theme"
license = "MIT"
licenselink = "https://github.com/yourname/docs-theme/blob/master/LICENSE"
description = "A documentation theme with language variant support"
homepage = "http://example.com/"
tags = ["docs", "documentation", "responsive"]
features = ["language variants", "sidebar navigation"]
min_version = "0.41.0"

[author]
  name = "Nelson Araujo"
  homepage = "https://docs.union.ai/"