on:
  pull_request:
    branches:
      - main

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

      - name: Astral UV sync
        run: uv sync

      - name: Build
        run: uv run make build
