name: Check Jupyter Notebooks

on: [push]

jobs:
  check-jupyter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0  # Fetch all history for proper git operations

      - name: Run Jupyter notebook validation
        run: ./tools/jupyter_generator/check_jupyter.sh

      - name: Report status
        if: ${{ failure() }}
        run: |
          echo "::error::Jupyter notebook validation failed. Please ensure all notebooks are properly synced and content hashes are up-to-date."
